sys = {'impl_dsgn',...
    'impl_dsgn/ITU-R BT.709',...
    'impl_dsgn/Noise Generator',...
    'impl_dsgn/Noise Generator/Permanent Noise',...
    'impl_dsgn/Noise Generator/Transient Noise',...
    'impl_dsgn/Noise Filtering',...
    'impl_dsgn/Verification - 1',...
    'impl_dsgn/Display Reference',...
    'impl_dsgn/Display Filtered Frame',...
    'impl_dsgn/Display Noisy Frame',...
    'impl_dsgn/Display Noise Identification Frame',...
    'impl_dsgn/Noise Identification',...
    'impl_dsgn/Video Overlay',...
    'impl_dsgn/Permanent Noise Count',...
    };

for k=1:length(sys)
    print(['-s',sys{k}],'-dpdf',['pdf-snapshots/',strrep(sys{k},'/','_'),'.pdf'])
end